apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nginx-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-gateway.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ .Values.podDisruptionBudget.unhealthyPodEvictionPolicy }}
  {{- end }}
  selector:
    matchLabels:
    {{- include "nginx-gateway.selectorLabels" . | nindent 6 }}
